purism-chatty: upgrade to 0.1.17.
This is the last version we can use without needing Google's
libphonenumber, which can't cross-compile and still results in this
program having an undefined reference to symbol
'_ZN6icu_6712RegexPattern7compileERKNS_13UnicodeStringEjR11UParseErrorR10UErrorCode'
in libphonenumber.a(regexp_adapter_icu.cc.o) :(